project_id = "arsetehgavxmkwkieedm"

[functions.strava-oauth-callback]
verify_jwt = false

[functions.strava-auth-exchange]
verify_jwt = false

[functions.get-uetliberg-segments]
verify_jwt = true

[functions.get-uetliberg-runs]
verify_jwt = true